[basepaths]
    ft = 'C:\Git_Workspace\Computer_Vision_Fork\ex05\PretrainedModels\OpticalFlowFinetunedModels'
    pt = 'C:\Git_Workspace\Computer_Vision_Fork\ex05\PretrainedModels\OpticalFlowPretrainedModels'
[pt]
    [pt.flownetc]
        ckpt = 'flownet_c\checkpoint-model-iter-000600000.pt'
    [pt.flownets]
        ckpt = 'flownet_s\checkpoint-model-iter-000600000.pt'
[ft]
    [ft.flownets-sintel10k-sup]
        ckpt = 'flownet_s_ftsintel10ksup\checkpoint-model-iter-000610000.pt'
    [ft.flownets-sintel10k-photosmooth]
        ckpt = 'flownet_s_ftsintel10kphotosmooth\checkpoint-model-iter-000610000.pt'
