[FlyingThings3D]
    [FlyingThings3D.train]
        root = '/project/cv-ws2324/shared-data/FlyingThings3D/TRAIN'
    [FlyingThings3D.test]
        root = '/project/cv-ws2324/shared-data/FlyingThings3D/TEST'

[Sintel]
    root = '/project/cv-ws2324/shared-data/Sintel/data/training'

[FlyingChairs]
    root = '/project/cv-ws2324/shared-data/FlyingChairs/data'
